# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  cunaguaro product cataloge

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: hello-from-lambda.js
  EmailQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Join
      - '-'
      - - cunaguaro
        - product-catalog
        - !Ref 'AWS::Region'
        - !Ref 'AWS::AccountId'
        - emailqueue
  getHomePage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-home-page.getHomePageHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: A Lambda function that returns a static string.
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
  GeneratePDF:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/generate-pdf.generatePDF
      Runtime: nodejs12.x
      Timeout: 20
      Environment:
        Variables:
          WEBSITE_S3_BUCKET: !Join
          - '-'
          - - cunaguaro
            - product-catalog
            - !Ref 'AWS::Region'
            - !Ref 'AWS::AccountId'
            - pdf
            - files
          EMAIL_SQS: !Ref EmailQueue
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /generate-pdf
            Method: post
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket

